worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Security
    server_tokens off;

    # Compression
    gzip on;
    gzip_types application/json text/plain;
    gzip_min_length 256;

    include /etc/nginx/conf.d/*.conf;
}
